#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


BLUE='\033[44m'
RED='\033[101m'
YELLOW='\033[103m'
GREEN='\033[42m'
NC='\033[0m' # No Color

RED_COLOR='\033[31m'
YELLOW_COLOR='\033[93m'
GREEN_COLOR='\033[92m'

border () {
    local str="$*"      # Put all arguments into single string
    local len=${#str}
    local i
    for (( i = 0; i < len - 30; ++i )); do
        printf "${GREEN_COLOR}-"
    done
    printf "\n${GREEN_COLOR}| ${NC}$str \n"
    for (( i = 0; i < len - 30; ++i )); do
        printf "${GREEN_COLOR}-"
    done
    echo
}


parse_git_user() {
  git config --get user.name
}
parse_current_branch() {
  git rev-parse --abbrev-ref HEAD
}

now="$(date +'%A %H:%M:%S %d/%m/%Y %Z')"


border "${RED_COLOR}>${YELLOW_COLOR}>${GREEN_COLOR}>${NC} Hello $(parse_git_user). You are ${GREEN_COLOR}pushing${NC} on: ${BLUE}$(parse_current_branch)${NC} branch ($now) 😍"
printf "${RED_COLOR}>${YELLOW_COLOR}>${GREEN_COLOR}>${NC} I'm check lint for you ...${NC}\n"
npx pretty-quick --staged && npm run lint:ts
printf "${RED_COLOR}>${YELLOW_COLOR}>${GREEN_COLOR}>${NC} All lint are ${GREEN_COLOR}okela${NC} ❤️  ❤️  ❤️️\n"
